root: true
parser: '@typescript-eslint/parser'
plugins:
    - '@typescript-eslint'
extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'prettier'
rules:
    '@typescript-eslint/no-explicit-any': 1
    '@typescript-eslint/no-non-null-assertion': 1
overrides:
    - files: ['*.ts', '*.tsx']
      extends:
          - 'plugin:@typescript-eslint/recommended'
          - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
      parserOptions:
          project: ['./tsconfig.json']
ignorePatterns:
    - 'dist/**/*'
